### PR TITLE
added logic to update both home/xonfig.xml and install.xml if they ex…

### PR DESCRIPTION
**Pull request by mattohope**
…ists

### CODE REVIEW

**Comment by jonmort** [comment]
Why update the copyright date?

**Comment by mattohope** [comment]
I can revert, as it's in active development I thought it best to update the copyright, happy to revert to 2015

**Comment by jonmort** [comment]
Only reason to update the copyright date is if it was a mistake to state that date in the first place. The date establishes the earliest date from which we are making the claim of copyright. AFAIK the only time you want to update the date is if you substantially change the work, and in that case you would only want to add an additional year, not update the original. Probably best to reset to remove that commit. See https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated for more background

**Comment by mattohope** [comment]
Ok i've removed the changes to copyright

**Pull request merged**
